[workspace]
members = [
    "src/ip_market_backend"
]
resolver = "2"

# Optimize for size in release builds
[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.release.package.ic-wasm]
opt-level = 2
